# Generated by Django 3.0.4 on 2020-03-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharityVolounteerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('GENDER', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=50)),
                ('Address', models.CharField(max_length=255)),
                ('organization_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LogisticComanyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('GENDER', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=50)),
                ('Address', models.CharField(blank=True, max_length=255, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_ownership', models.BooleanField(default=False)),
            ],
        ),
    ]
