# Generated by Django 3.0.4 on 2020-03-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cracgroupapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logisticcomanymodel',
            old_name='Address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='charityvolounteermodel',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='charityvolounteermodel',
            name='GENDER',
        ),
        migrations.RemoveField(
            model_name='logisticcomanymodel',
            name='GENDER',
        ),
        migrations.AddField(
            model_name='charityvolounteermodel',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='charityvolounteermodel',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logisticcomanymodel',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='charityvolounteermodel',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
