# Generated by Django 3.0.4 on 2020-03-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cracgroupapp', '0002_auto_20200329_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolounteerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_charity_org', models.BooleanField(default=False)),
                ('is_logistic_company', models.BooleanField(default=False)),
                ('vehicle_ownership', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='CharityVolounteerModel',
        ),
        migrations.DeleteModel(
            name='LogisticComanyModel',
        ),
    ]
