# Generated by Django 3.0.4 on 2020-03-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cracgroupapp', '0004_remove_volounteermodel_vehicle_ownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=100)),
                ('txnstatus', models.CharField(max_length=50)),
                ('txnref', models.CharField(max_length=250)),
                ('bankmessage', models.CharField(max_length=250)),
                ('paymentmethod', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('message', models.CharField(max_length=250)),
                ('fraudstatus', models.CharField(max_length=50)),
                ('cardtoken', models.CharField(max_length=250)),
            ],
        ),
    ]
