# Generated by Django 3.0.4 on 2020-03-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cracgroupapp', '0005_paymentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='cardtoken',
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='bankmessage',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='fraudstatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='fullname',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='message',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='paymentmethod',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='txnref',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='txnstatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
