# Generated by Django 3.0.4 on 2020-03-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cracgroupapp', '0006_auto_20200330_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='amount',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
