# Generated by Django 3.0.4 on 2020-04-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cracgroupapp', '0007_auto_20200330_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDonationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.CharField(max_length=250)),
                ('pickup_location', models.CharField(blank=True, max_length=255, null=True)),
                ('distribution', models.CharField(blank=True, max_length=500, null=True)),
                ('delivery_date', models.DateField()),
            ],
        ),
    ]
