# Generated by Django 3.0.4 on 2020-04-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cracgroupapp', '0008_productdonationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='volounteermodel',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
