# Generated by Django 3.0.4 on 2020-04-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cracgroupapp', '0009_volounteermodel_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdonationmodel',
            old_name='distribution',
            new_name='product_description',
        ),
        migrations.AddField(
            model_name='productdonationmodel',
            name='product_distribution',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
