# Generated by Django 3.0.4 on 2020-04-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cracgroupapp', '0010_auto_20200402_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdonationmodel',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
