# Generated by Django 3.0.4 on 2020-04-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cracgroupapp', '0011_auto_20200402_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='JointDonatorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JointDonationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=150)),
                ('unit_price', models.IntegerField()),
                ('donated_amount', models.IntegerField(default=0)),
                ('donation_circle', models.IntegerField(default=0)),
                ('donation_count', models.IntegerField(default=0)),
                ('donators', models.ManyToManyField(to='cracgroupapp.JointDonatorModel')),
            ],
        ),
    ]
