# Generated by Django 3.0.4 on 2020-04-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cracgroupapp', '0012_jointdonationmodel_jointdonatormodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jointdonationmodel',
            name='product',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
