# Generated by Django 3.0.4 on 2020-04-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cracgroupapp', '0013_auto_20200402_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volounteermodel',
            name='is_charity_org',
        ),
        migrations.RemoveField(
            model_name='volounteermodel',
            name='is_logistic_company',
        ),
        migrations.AddField(
            model_name='volounteermodel',
            name='partner_as',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='volounteermodel',
            name='volunteer_as',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
