# Generated by Django 3.0.4 on 2020-04-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cracgroupapp', '0014_auto_20200406_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jointdonationmodel',
            name='donators',
        ),
        migrations.AddField(
            model_name='jointdonationmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_image'),
        ),
        migrations.AlterField(
            model_name='jointdonationmodel',
            name='product',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='jointdonationmodel',
            name='unit_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='JointDonatorModel',
        ),
    ]
