# Generated by Django 3.0.4 on 2020-04-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cracgroupapp', '0015_auto_20200406_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='jointdonationmodel',
            name='unit',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
