# Generated by Django 3.0.4 on 2020-04-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cracgroupapp', '0017_auto_20200406_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='jointdonationmodel',
            name='ongoing_circle_count',
            field=models.IntegerField(default=0),
        ),
    ]
