# Generated by Django 3.0.4 on 2020-04-07 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cracgroupapp', '0018_jointdonationmodel_ongoing_circle_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jointdonationmodel',
            name='donation_circle',
        ),
    ]
